### ISSUE TITLE
Gender argument does not work

### ISSUE THREAD

**Issue by karthik** [RandomAPI/Randomuser.me-Data#10]
```
http://api.randomuser.me/?gender=female
```

You can see this by reloading that URL a few times.

**Comment by solewolf** [comment]
Thanks for the report @karthik,
The gender parameter should be working properly now.

**Comment by karthik** [comment]
Awesome, thanks @solewolf 
I wrote a R package to work with your API. People can also use it with their paid API keys. Check it out: 
https://github.com/karthik/randNames

**Comment by solewolf** [comment]
Looks pretty neat @karthik! Thanks for the R Package.
I sent in a pull request to clear some things up about the RandomAPI.com API key and requesting more than 100 users.

I am gonna see if I can elucidate the documentation a bit better.
