### ISSUE TITLE
Nationality parameter does not work

### ISSUE THREAD

**Issue by karthik** [RandomAPI/Randomuser.me-Data#11]
Related to issue #10, the nationality parameter also doesn't work. It randomly returns US or GB. It might require the same fix.

**Comment by solewolf** [comment]
It looks like it is working for me?
```
http://api.randomuser.me/?nat=us
```
```
http://api.randomuser.me/?nat=gb
```

Could you provide an example of how you are formatting your URL/parameters?

**Comment by karthik** [comment]
It was a mistake at my end. I was passing `nationality` instead of `nat`. Fixed now. Thanks for the quick response.
