### ISSUE TITLE
Capitalize proper nouns

### ISSUE THREAD

**Issue by wagonerwebworks** [RandomAPI/Randomuser.me-Data#12]
Would save some frustration and headaches of end-users not having to implement their own capitalizing functions

**Comment by solewolf** [comment]
Hi @wagonerwebworks! The reason why we don't capitalize proper nouns and don't format the timestamps of registered/dob is to keep the data in as "pure" a state as possible.

Many users use different formats for data, so by using the timestamps in place of a date like 12/25/2015 or by setting the proper nouns to all lowercase vs Dallas/DALLAS, we are able to leave the data in its simplest form for modification.
