### ISSUE TITLE
C# Libary for using Data-Generator-RandomUser

### ISSUE THREAD

**Issue by RaviRamDhali** [RandomAPI/Randomuser.me-Data#25]
I have shared C# code for using and displaying data from RandomAPI/Randomuser.me-Data

https://github.com/RaviRamDhali/programming-procedure/blob/master/Snippets/C-Sharp/Data-Generator-RandomUser

**Comment by keitharm** [comment]
Thanks! Looks cool :)

One suggestion though: Since we now have multiple nationalities, not all of the results will contain a zip, city, etc. which might break your code.

Some fields are different depending on the nationality that is chosen.
