### ISSUE TITLE
Irish (IE) version of data does not include a City in location

### ISSUE THREAD

**Issue by coolgarriv** [RandomAPI/Randomuser.me-Data#33]
The Irish data generated does not include a City. Also It includes a State and a Zip. See http://api.randomuser.me/?nat=ie for an example.

The correct format for Irish addresses is as follows:
[Firstname] [Lastname]
[Street Address]
[City name]
Co. [Countyname]

State is not required, but postcodes are being introduced in Summer 2015.

**Comment by keitharm** [comment]
State will be removed in the next update.
Could you please provide the format of the postcodes and also a city list?

Thanks

**Comment by coolgarriv** [comment]
Format for postcode hasn't been officially released yet, but according to https://www.eircode.ie/what-is-eircode it is 1 letter followed by 2 numbers, followed by a space followed 4 letters and/or numbers. 

I will update when the formatting has been officially released and I will create a list of cities.

**Comment by keitharm** [comment]
Ok sounds good! I've merged your list of cities and I guess for now we can use the postcode format you found.

If it changes, we can always update the IE API.

The changes will be in the next API update.
