### ISSUE TITLE
Can we have some params for the API 

### ISSUE THREAD

**Issue by murliatdure** [RandomAPI/Randomuser.me-Data#38]
- Limit (already there as results)
- Gender (Male/Female)

And probably AGE limited avtars 
- say I am looking for 50-60 age users (for demonstrations)

**Comment by keitharm** [comment]
Hi @murliatdure,

Currently we've separated the images only based on male/female. We then choose a random image based on the gender.

We don't have any other data regarding race, age, height, etc. so we wouldn't be able to readily implement this.
