### ISSUE TITLE
Random user api is down

### ISSUE THREAD

**Issue by kharazi** [RandomAPI/Randomuser.me-Data#42]
Hi, 
There is a problem in [randomuser.me/api ](https://randomuser.me/api/). Please fix it cuz I'm testing my project with it! ;) tnx

```
504 Gateway Time-out
````

**Comment by daniel-shin1104** [comment]
+1. I ran a quick nmap on the domain and it seems the domain is being transferred / revoked.

**Comment by jtammen** [comment]
Works for me (again).
