### ISSUE TITLE
Thumb and full-size images for the random number do not match

### ISSUE THREAD

**Issue by rohanbritto** [RandomAPI/Randomuser.me-Data#52]
For example:
https://randomuser.me/api/portraits/women/11.jpg
and
https://randomuser.me/api/portraits/thumb/women/11.jpg
are 2 different women.

This also leads to problems on your website. Steps to reproduce the issue are as follows:
1. Visit the following link https://randomuser.me/photos
2. Click on any thumbnail to view the full-size image of the person.
3. You will see a different image.

**Comment by keitharm** [comment]
Fixed! Thanks for the report!
